#!/bin/sh
# Configuration script for bspwm. Automatically handles multiple monitors,
# assigning an equal number of workspaces for each of them. It also starts
# up some programs in case they're available.
#
# The --restart flag can be passed in order to only restart the necessary
# parts of this script when restarting.

start_program() {
    # Starts a program (with arguments) in case it exists. It will also kill
    # all previously running instances.
    if command -v "$1" >/dev/null 2>&1; then
        killall -q "$1"
        "$@" &
    fi
}

BROWSER=firefox
TERMINAL=alacritty
WALLPAPER=~/Files/dotfiles/wallpaper.png
MAX_WORKSPACES=10
NUM_MONITORS=$(xrandr | awk '/ connected / {print $1}' | wc -l)
WPM=$((MAX_WORKSPACES / NUM_MONITORS))


### BSPWM CONFIG ###
# Calculating what workspaces are going to be used for each monitor
# automatically.
xrandr | awk -v "count=1" -v "wpm=$WPM" '/ connected / {
    count += wpm;
    print $1, (count - wpm), (count - 1)
}' | while read -r monitor begin end; do
    workspaces=$(seq "$begin" "$end" | tr '\n' ' ')
    bspc monitor "$monitor" -d  $workspaces
done

# Borders and gaps
bspc config border_width 2
bspc config window_gap 8
bspc config normal_border_color "#282828"
bspc config focused_border_color "#f1f1f1"
bspc config active_border_color "#6b6b6b"
bspc config urgent_border_color "#ab0000"
# No gaps/borders with only one window in the workspace
bspc config leaf_monocle true
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

# Mouse
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Programs
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a MEGAsync state=floating border=off


### AUTOSTART ###
# Hotkey daemon
start_program sxhkd

# Status bar
# Polybar with a custom script
~/.config/polybar/launch.sh &

# Wallpaper
feh --bg-fill "$WALLPAPER" &

# Compositor
start_program picom

# Notification daemon
start_program dunst

# Redshift
start_program redshift-gtk -l "[REMOVED]"

# Network Manager's applet
if systemctl list-units | grep -q networkmanager; then
    start_program nm-applet
fi

# Bluetooth applet
if lsusb | grep Bluetooth; then
    start_program blueman-applet
fi

# Only open the initial programs with the restart flag
if [ "$1" != "--restart"  ]; then
    # The browser in first workspace
    bspc rule -a "$BROWSER" desktop=^1 --one-shot
    "$BROWSER" &

    # A terminal in the second workspace, or second monitor if there's more
    # than one.
    if [ "$NUM_MONITORS" -eq 1 ]; then
        bspc rule -a "$TERMINAL" desktop=^2 --one-shot
    else
        bspc rule -a "$TERMINAL" desktop=^6 --one-shot
    fi
    "$TERMINAL" &
fi
